# Generated by Django 3.2.15 on 2022-08-23 18:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LoanOffers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apr', models.PositiveIntegerField(blank=True, null=True)),
                ('monthly_payments', models.PositiveIntegerField(blank=True, null=True)),
                ('term_length_months', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('accept', models.BooleanField(blank=True, null=True)),
                ('reasons', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_offers', to='api.users')),
            ],
        ),
        migrations.CreateModel(
            name='LoanApplications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_score', models.PositiveSmallIntegerField()),
                ('monthly_debt', models.PositiveIntegerField()),
                ('monthly_income', models.PositiveIntegerField()),
                ('bankruptcies', models.PositiveSmallIntegerField()),
                ('delinquencies', models.PositiveSmallIntegerField()),
                ('vehicle_value', models.PositiveIntegerField()),
                ('loan_amount', models.PositiveIntegerField()),
                ('loan_offer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_application', to='api.loanoffers')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='api.users')),
            ],
        ),
    ]
